### PR TITLE
Adding two performance tests showing performance slow with increased history

### PR DESCRIPTION
**Pull request by adamwulf**
`testFirst1kEdits()` Tests buliding a document and modifying a `CGPoint` attribute 1000 times. These first 1000 edits of a document take roughly 1.5s on my machine, which is slower than I'd expect for changing a single attribute.

`testSubsequent1kEdits` is the interesting one. This measures subsequent 1000 edits to the same document. This is very similar to the first test, but has an average runtime of 12 seconds - not 1.5s. The difference is that each subsequent 1000 edits is slower than the 1000 before. The cost/edit seems to be proportional to the history size of the document. Is this expected behavior? I would expect the cost of an edit to be fairly constant.

### CODE REVIEW

**Comment by lightsprint09** [comment]
Can you please test this on the #28 Branch. We did some optimizations which improved performance.

It looks like you did not push the test cases itself. Just the baseline configurations

**Comment by adamwulf** [comment]
ah oops! just pushed up the test file. i'll give it a go on #28 too

**Comment by adamwulf** [comment]
It is better, though still proportional to edit history it appears. On the #28 branch, `testFirst1kEdits()` is 1.2s while `testSubsequent1kEdits()` is about twice as fast, averaging 6s with a max of 12s instead of 25s for that final 1000 edits

**Comment by endeavour42** [comment]
here's what i'm getting on my computer.

original test, subsequent runs on the same "doc" object:

 912   52%  updateRootObject, overall time: 1759 ms
2810   72%  updateRootObject, overall time: 3884 ms
4669   77%  updateRootObject, overall time: 6027 ms
7427   78%  updateRootObject, overall time: 9479 ms
9178   80%  updateRootObject, overall time: 11426 ms

here updateRootObject dominates everything else and performance slows down.

modified test (has explicit x & y and sets them individually), subsequent runs on the same "doc" object:

   3    1%  updateRootObject, overall time: 690 ms
   3    1%  updateRootObject, overall time: 693 ms
   3    0%  updateRootObject, overall time: 699 ms
   3    0%  updateRootObject, overall time: 684 ms
   3    1%  updateRootObject, overall time: 687 ms

here updateRootObject takes very little and performance stays constant.

in the modified version i'm doing:
    proxy.x.set(p.x)
    proxy.y.set(p.y)
instead of:
   proxy.fumble.set(p)

and having explicit x & y in the model instead of CGPoint.

**Comment by endeavour42** [comment]
with the latest changes from Lukas still increasing time but much better performance for the original test:

overall time: 873 ms
overall time: 1063 ms
overall time: 1419 ms
overall time: 1664 ms
overall time: 1849 ms
overall time: 2158 ms
overall time: 2821 ms

the performance of modified test is constant time, 740 ms (slightly worse than before).

**Pull request closed without merging**
